// lib/pdfUtils.ts
import { jsPDF } from "jspdf";

export interface PDFOptions {
  title: string;
  subtitle?: string;
  orientation?: "portrait" | "landscape";
}

/**
 * Creates a new jsPDF instance with UnMess branding and watermark
 */
export const createUnMessPDF = (options: PDFOptions): jsPDF => {
  const { title, subtitle, orientation = "portrait" } = options;
  const doc = new jsPDF({ orientation });

  // Add Header with UnMess branding
  addUnMessHeader(doc, title, subtitle);

  return doc;
};

/**
 * Adds UnMess branded header to the PDF (Invoice-style design)
 */
const addUnMessHeader = (doc: jsPDF, title: string, subtitle?: string) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Purple decorative corner (top left)
  doc.setFillColor(126, 34, 206); // #7E22CE
  doc.triangle(0, 0, 60, 0, 0, 20, "F");

  // Purple decorative corner (top right)
  doc.triangle(pageWidth, 0, pageWidth - 60, 0, pageWidth, 20, "F");

  // Brand Name "UnMess" on left side
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  // "Un" in dark gray (simulating white effect)
  doc.setTextColor(60, 60, 60);
  doc.text("Un", 14, 21);

  const unWidth = doc.getTextWidth("Un");

  // "Mess" in purple
  doc.setTextColor(126, 34, 206);
  doc.text("Mess", 14 + unWidth, 21);

  // Document title (like "INVOICE") on right side
  doc.setFontSize(18);
  doc.setTextColor(126, 34, 206);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), pageWidth - 14, 23, { align: "right" });

  // Horizontal separator line
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.8);
  doc.line(14, 31, pageWidth - 14, 31);

  // Subtitle/Additional info (invoice number style)
  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, pageWidth - 14, 39, { align: "right" });
  }
};

/**
 * Adds section header (invoice-style with box)
 */
export const addSectionHeader = (
  doc: jsPDF,
  text: string,
  yPosition: number
) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Light background box
  doc.setFillColor(250, 250, 250);
  doc.rect(14, yPosition - 1, pageWidth - 28, 8, "F");

  // Section text
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.text(text, 17, yPosition + 4);
};

/**
 * Adds UnMess branded footer to the PDF (invoice-style)
 */
export const addUnMessFooter = (doc: jsPDF, pageNumber?: number) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Purple decorative corner (bottom left)
  doc.setFillColor(126, 34, 206);
  doc.triangle(0, pageHeight, 60, pageHeight, 0, pageHeight - 20, "F");

  // Purple decorative corner (bottom right)
  doc.triangle(
    pageWidth,
    pageHeight,
    pageWidth - 60,
    pageHeight,
    pageWidth,
    pageHeight - 20,
    "F"
  );

  // Center footer text
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "normal");

  const date = new Date().toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const footerText = `Generated by UnMess App | ${date}`;
  const textWidth = doc.getTextWidth(footerText);
  const centerX = pageWidth / 2;
  doc.text(footerText, centerX - textWidth / 2, pageHeight - 8);

  if (pageNumber) {
    doc.setFontSize(8);
    doc.setTextColor(126, 34, 206);
    doc.setFont("helvetica", "bold");
    doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 8, {
      align: "right",
    });
  }
};

/**
 * Adds watermark to center of page
 */
export const addWatermark = (doc: jsPDF) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.saveGraphicsState();
  doc.setTextColor(126, 34, 206);
  doc.setFontSize(60);
  doc.setFont("helvetica", "bold");

  const watermarkText = "UnMess";
  const gState = (doc as any).GState
    ? new (doc as any).GState({ opacity: 0.03 })
    : undefined;
  if (gState) {
    doc.setGState(gState);
  }

  const textWidth = doc.getTextWidth(watermarkText);
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;

  doc.text(watermarkText, centerX - textWidth / 2, centerY, {
    angle: 45,
  });

  doc.restoreGraphicsState();
};

/**
 * Common table styles for UnMess PDFs - Modern professional design
 */
export const getUnMessTableStyles = () => ({
  theme: "grid" as const,
  headStyles: {
    fillColor: [126, 34, 206] as [number, number, number], // Brand purple
    textColor: [255, 255, 255] as [number, number, number],
    fontStyle: "bold" as const,
    fontSize: 9,
    halign: "center" as const,
    valign: "middle" as const,
    cellPadding: { top: 6, right: 8, bottom: 6, left: 8 },
    lineWidth: 0,
  },
  bodyStyles: {
    textColor: [45, 55, 72] as [number, number, number], // Slate gray
    fontSize: 9,
    cellPadding: { top: 5, right: 8, bottom: 5, left: 8 },
    lineWidth: 0.1,
    lineColor: [226, 232, 240] as [number, number, number], // Light slate border
  },
  alternateRowStyles: {
    fillColor: [248, 250, 252] as [number, number, number], // Very light slate
  },
  styles: {
    lineColor: [226, 232, 240] as [number, number, number],
    lineWidth: 0.1,
    fontSize: 9,
    overflow: "linebreak" as const,
    cellWidth: "auto" as const,
    minCellHeight: 8,
  },
  columnStyles: {
    0: { halign: "left" as const, fontStyle: "normal" as const },
  },
});

/**
 * Applies watermark and footers to all pages
 */
export const applyWatermarkToAllPages = (doc: jsPDF) => {
  const totalPages = (doc as any).internal.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Add watermark
    addWatermark(doc);

    // Add footer
    addUnMessFooter(doc, i);
  }
};

export default {
  createUnMessPDF,
  addUnMessFooter,
  addSectionHeader,
  getUnMessTableStyles,
  applyWatermarkToAllPages,
};
